import { Toaster } from "react-hot-toast";
import "./globals.css";
import ContextProvider from "@/context/SocketContext";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>

        {children}
        <Toaster position="top-right" />
        </ContextProvider>
      </body>
    </html>
  );
}
